In [ ]:
# in case of new notebook, use the commented code to load the data:

import pandas as pd

file1 = pd.read_csv('file1.csv')
file2 = pd.read_csv('/content/drive/MyDrive/CURR-v3.X-FEB2022/UNIT1/DAY2/JAN/1.04 Exploration and Data Cleaning/file2.txt', sep = '\t')
file3 = pd.read_excel('/content/drive/MyDrive/CURR-v3.X-FEB2022/UNIT1/DAY2/JAN/1.04 Exploration and Data Cleaning/file3.xlsx', engine="openpyxl")
file4 = pd.read_excel('/content/drive/MyDrive/CURR-v3.X-FEB2022/UNIT1/DAY2/JAN/1.04 Exploration and Data Cleaning/file4.xlsx', engine="openpyxl")

column_names = file1.columns
donors = pd.DataFrame(columns=column_names)
donors = pd.concat([file1,file2,file3,file4], axis=0)

cols = []
for colname in donors.columns:
    cols.append(colname.lower())
donors.columns = cols

donors = donors.rename(columns={'controln':'id',
                                'hv1':'median_home_val', 
                                'ic1':'median_household_income'})

donors['median_home_val'] =  pd.to_numeric(donors['median_home_val'], errors='coerce')
donors['ic5'] =  pd.to_numeric(donors['ic5'], errors='coerce')
donors = donors.drop_duplicates()

donors.shape

(4001, 17)

In [ ]:
print(donors.dtypes)
display(donors)

id                           int64
state                       object
gender                      object
median_home_val            float64
median_household_income      int64
ic4                        float64
hvp1                         int64
ic5                        float64
pobc1                        int64
pobc2                        int64
ic2                        float64
ic3                          int64
avggift                    float64
tcode                        int64
dob                          int64
domain                      object
target_d                   float64
dtype: object

          id state gender  median_home_val  ...  tcode   dob  domain  target_d
0      44060    FL      M              NaN  ...      1  1901      C2     100.0
1      96093    IL      M            537.0  ...      0     0      T2       7.0
2      43333    FL      F            725.0  ...      0  2501      C2       5.0
3      21885    NC      M              NaN  ...      0  2208      T2      38.0
4     190108    FL      F            995.0  ...     28     0      C2       5.0
...      ...   ...    ...              ...  ...    ...   ...     ...       ...
996    66762    MI      F            632.0  ...      0     0       0       5.0
997     6443    FL      M            595.0  ...      1  2501      T2      20.0
998   151175    CA      F           2707.0  ...      0  4001      U1      22.0
999   151504    CA      M           2666.0  ...      1  4401      S1      21.0
1000   74303    MI      M            444.0  ...      4   405      R2      25.0

[4001 rows x 17 columns]

In [ ]:
donors.shape[0]

4001

In [ ]:
#pd.DataFrame(columns = ['A','B','C'])

Empty DataFrame
Columns: [A, B, C]
Index: []

In [ ]:
#donors.isna().sum()
# pd.DataFrame()
#round(donors.isna().sum()/donors.shape[0],4)*100
#round(donors.isna().sum()/len(donors),4)*100  # shows the percentage of null values in a column
nulls_df = pd.DataFrame(round(donors.isna().sum()/len(donors),4)*100)
#display(nulls_df)
nulls_df = nulls_df.reset_index()
display(nulls_df)
nulls_df.columns = ['header_name', 'percent_nulls']
display(nulls_df.head())

                      index     0
0                        id  0.00
1                     state  0.00
2                    gender  3.32
3           median_home_val  0.25
4   median_household_income  0.00
5                       ic4  0.02
6                      hvp1  0.00
7                       ic5  0.15
8                     pobc1  0.00
9                     pobc2  0.00
10                      ic2  0.02
11                      ic3  0.00
12                  avggift  0.00
13                    tcode  0.00
14                      dob  0.00
15                   domain  0.00
16                 target_d  0.00

               header_name  percent_nulls
0                       id           0.00
1                    state           0.00
2                   gender           3.32
3          median_home_val           0.25
4  median_household_income           0.00

In [ ]:
nulls_df[nulls_df['percent_nulls']>3]

  header_name  percent_nulls
2      gender           3.32

In [ ]:
columns_drop = nulls_df[nulls_df['percent_nulls']>3]['header_name']  # dummy case with 3
display(columns_drop)
#donors = donors.drop(columns_drop, axis=1)  # drop a list of columns DO NOT RUN THIS
#donors = donors.drop(['gender'], axis=1)  # drop a single column DO NOT RUN THIS

2    gender
Name: header_name, dtype: object

In [ ]:
# Replacing/imputing null values
donors[donors['gender'].isna()==True].head(60) # checking rows that are null based on a specific column

         id       state gender  median_home_val  ...  tcode   dob  domain  target_d
15    73699          MI    NaN            890.0  ...      1  5102      S1      15.0
21   114721          OK    NaN           1040.0  ...      0     0      C2      15.0
22   111795          AR    NaN            603.0  ...      0     0       0       5.0
54   190671          CA    NaN           2143.0  ...      0  1901       0      14.0
77   156324        Cali    NaN           2016.0  ...      0     0      S1      15.0
84    60512          IL    NaN           1055.0  ...      2  2801      S2      25.0
94    37118          FL    NaN            581.0  ...      0  2607      S2      15.0
130   35276          FL    NaN           3542.0  ...      2  1701      C1      10.0
151  156568          CA    NaN           3020.0  ...      0  4812      S1      75.0
186  187571          IN    NaN            561.0  ...      0     0      R2      26.0
195   41715          FL    NaN            696.0  ...      0     0      U3       3.0
217    8240          CA    NaN           1187.0  ...      1     0       0      10.0
239  188164          TX    NaN           1362.0  ...      0     0      S1      10.0
345  187298          SC    NaN           1015.0  ...      0     0      S1      10.0
353  149626          NV    NaN           1557.0  ...      0     0      S1      10.0
374  153450  California    NaN           1865.0  ...      0     0      U3      47.0
406  169780  California    NaN           1650.0  ...      0     0      C2      10.0
420  148998  California    NaN           3233.0  ...      1  4709      C1      25.0
445  178826          CO    NaN            872.0  ...      0  5102      S1      20.0
470  142057          NV    NaN           2479.0  ...      0   904      T1      15.0
489  148354  California    NaN           2206.0  ...      0     0      S1       8.0
495  165302  California    NaN           2811.0  ...      0  2207      C1      20.0
521  130756          CO    NaN           2408.0  ...      0  4701      T1      20.0
522   87281          MT    NaN            445.0  ...      0     0      R2       8.0
524   20065          NC    NaN            722.0  ...     28  5301      T2      40.0
594  188035          AZ    NaN           1165.0  ...      1     0      S1      23.0
624  130684          AL    NaN           1175.0  ...    980     0      T1       6.0
669  169605  California    NaN           1185.0  ...      0     0      C3       7.0
670  157573  California    NaN           2438.0  ...      0     0      S1      47.0
682  146703  California    NaN            675.0  ...      1     0      C3      15.0
720  114676          OK    NaN           1062.0  ...      0  5201      T1      20.0
740  113045          OK    NaN            699.0  ...      0     0      T2      25.0
786     263          SC    NaN           2156.0  ...      2  2001      T1      10.0
819  185760          GA    NaN            659.0  ...      0     0      C2      10.0
869  175438          OR    NaN            925.0  ...      3  2001      U2      25.0
870   68427          MI    NaN            483.0  ...      0     0      U2      25.0
895   10893          CA    NaN           2012.0  ...      0     0      R1      20.0
964   63000          IN    NaN            351.0  ...      0     0      T3      25.0
986   27846          GA    NaN           1149.0  ...      0     0      C2     200.0
10   167039          CA    NaN           3201.0  ...      0     0      S1       5.0
12   151653          CA    NaN           1455.0  ...      0  2401      U3      10.0
30   179377          WA    NaN           1617.0  ...      0     0       0      10.0
103   74701          MI    NaN            360.0  ...      1  1901      R3      20.0
114  151455          CA    NaN           2105.0  ...      0     0      U4      20.0
119   91965          IL    NaN           1708.0  ...      2  4505      S2      16.0
144   10709          WA    NaN            534.0  ...      0     0       0      23.0
148  187191          GA    NaN           2639.0  ...      0     0      C1      25.0
152  163369          CA    NaN           2250.0  ...      0     0      U2       6.0
164    2396          FL    NaN            588.0  ...      0     0      T2       5.0
181   40351          FL    NaN           1074.0  ...      0     0      S2      30.0
182   43321          FL    NaN           1452.0  ...      0  2301      C1      25.0
209  120608          TX    NaN            375.0  ...      0     0      C3      15.0
237   21107          NC    NaN            678.0  ...      1  1907      T2       7.0
296   77742          TX    NaN           1163.0  ...      0     0      R2       5.0
410  133176          ID    NaN           2111.0  ...      2  3601      R1      50.0
432  158567          CA    NaN           1722.0  ...      0  1110      S1       6.0
444  184269          WA    NaN            506.0  ...      0  1406      C2      10.0
511   28082          GA    NaN           1063.0  ...      0     0      T2      20.0
549  115676          TX    NaN            340.0  ...      4     0      T2      20.0
639   45551          FL    NaN              0.0  ...      2     0      S3      15.0

[60 rows x 17 columns]

In [ ]:
# drop rows that have null values (only if there are very few)
donors = donors[donors['ic2'].isna()==False] # Since these nulls are not a lot, we can filter them

donors.isna().sum()

id                           0
state                        0
gender                     133
median_home_val              9
median_household_income      0
ic4                          1
hvp1                         0
ic5                          6
pobc1                        0
pobc2                        0
ic2                          0
ic3                          0
avggift                      0
tcode                        0
dob                          0
domain                       0
target_d                     0
dtype: int64

In [ ]:
#donors['gender'] = donors['gender'].fillna("Unknown")

In [ ]:
# impute a value for the missing value (fill in a value that we choose or calculate)
# import numpy
import numpy as np
mean_median_home_value = donors['median_home_val'].mean()
print(mean_median_home_value)
donors['median_home_val'] = donors['median_home_val'].fillna(mean_median_home_value)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
#donors['median_home_val'] = donors['median_home_val'].fillna(donors['median_home_val'].mean())

In [ ]:
donors.isna().sum()

id                           0
state                        0
gender                     133
median_home_val              0
median_household_income      0
ic4                          1
hvp1                         0
ic5                          6
pobc1                        0
pobc2                        0
ic2                          0
ic3                          0
avggift                      0
tcode                        0
dob                          0
domain                       0
target_d                     0
dtype: int64

## Activity 1

You can find the instructions for this activity [here](https://github.com/ironhack-edu/data_1.04_activities/blob/master/1.04_activity_1.md)

In [ ]:
#Activity 1

In [ ]:
#End of Activity 1

In [ ]:
# Replacing null values for categorical variables
donors['gender'].unique()
donors['gender'].value_counts()

donors['gender'].value_counts(dropna=False)
#len(donors[donors['gender'].isna()==True])  # number of missing values

In [ ]:
# use most common value to fillna
donors['gender'] = donors['gender'].fillna('F')
len(donors[donors['gender'].isna()==True]) # now this number is 0

In [ ]:
# Exporting this processed data to a csv
donors.to_csv('merged_clean_ver1.csv') # you can find this file inside files_for_lesson_and_activities folder

In [ ]:
# lambda expressions

def add_two(x):
    #some code
    return x+2

# def do_something(lst,fun):
#      #some code
#      return result

# do_something([1,2,3],add_two)

add_two(4)

In [ ]:


y = lambda x: x+2
y(2)

square = lambda x: x*x
square(4)

addition = lambda x,y : x+y
addition(1,5)

# lst = [1,2,3,4,5,6,7,8,10]
# new_list = []
# for item in lst:
#     new_list.append(square(item))
# new_list

# new_list = [square(item) for item in lst] # list comprehension
# print(new_list)

# # new_list = [square(item) for item in lst if item%2==0]

## Activity 2

You can find the instructions for this activity [here](https://github.com/ironhack-edu/data_1.04_activities/blob/master/1.04_activity_2.md)

In [ ]:
#Activity 2

In [ ]:
# Refer to the file files_for_activities/merged_clean_ver1.csv for this exercise.

#1 Import the data from merged_clean_ver1.csv as a dataframe. There would be a column with the sequence of numbers (to the left of column id). Drop that column(s).

In [ ]:
# 2 Check the column state for null values. Replace those null values with the state that is represented largest number of times in that column

In [ ]:
# 3.1 Create a simple lambda expression to add three numbers. Take those three numbers as input from the user.

In [ ]:
# 3.2 Define a list as lst = [1,2,3,4,5,6,7,8,10]. 
#     Write a lambda expression to find the cube of a number.
#     Use that lambda expression to find the cube of every number in the list. 
#     Define a list comprehension for this question

In [ ]:
#End of Activity 2

In [ ]:
# map functions
#list(map(print, donors.columns))
#donors.columns = list(map(lambda x: x.lower(), donors.columns)) # we did this with a for loop earlier
# # donors
donors['gender'].unique() # check the unique values in the column
donors['gender'] = list(map(lambda x: x.upper(), donors['gender']))
donors['gender'].unique()

In [ ]:
donors['gender'].unique()  # check the unique elements in the column
# Now define a function to clean the column
def clean(x):
    if x in ['M', 'MALE']:
        return 'Male'
    elif x.startswith('F'):
        return 'Female'
    else:
        return 'U'

donors['gender'] = list(map(clean, donors['gender']))
donors['gender'].unique()  # To check the results again
donors

## Activity 3

You can find the instructions for this activity [here](https://github.com/ironhack-edu/data_1.04_activities/blob/master/1.04_activity_3.md)

In [ ]:
#Activity 3



# End of Activity 3

In [ ]:
# Examples of working with datetime format:

file = pd.read_csv('df_final_web_data_pt_1.csv')
file.dtypes

file['date_time'] = pd.to_datetime(file['date_time'], errors='coerce')
file.dtypes

In [ ]:
file['date_time'][0].day
# file['date_time'][0].month
# file['date_time'][0].year
# file['date_time'][0].isoweekday()  # Returns 1 for Monday and so on

# file['date_time'][0].time()
# file['date_time'][0].isoweekday()
# file['date_time'][0].isoformat()
# file['date_time'][0].strftime(format='%d-%m-%Y')
file['date_time'][0].strftime(format="%A %d. %B %Y")

In [ ]:
import time
from datetime import date

today = date.today()
today

# time.localtime(time.time())
# time.gmtime(time.time())

In [ ]:
# Examples of working with string functions

string = " I am learning  data  analysis at Ironhack  . It is  super easy "
string.lower
string.upper()
'34'.isdigit() # does not work with decimal numbers
str2 = '42'
str2.isdigit()
string = string.lstrip()
string.rstrip()
string.split()
string.split('.')
string.replace('%', '')

## Activity 4

You can find the instructions for this activity [here](https://github.com/ironhack-edu/data_1.04_activities/blob/master/1.04_activity_4.md)

In [ ]:
#Acticity 4
# Create a user-defined method to clean the column state in the dataframe.
# Use string functions to standardize the states to uppercase and use the strip function to clean the strings as well.

In [ ]:
#End Activity 4

In [ ]:
# Exporting this processed data to a csv
donors.to_csv('merged_clean_ver2.csv')